# Azure Container Instances - Docker Compose 네이티브 지원!
version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "80:8080"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=demo_db
      - DB_USERNAME=spring_user
      - DB_PASSWORD=secure_password_123
    depends_on:
      - mysql-db
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: demo_db
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: secure_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    restart: unless-stopped

volumes:
  mysql_data:

# Azure 배포 명령어:
# az container create --resource-group myResourceGroup --file azure-container-instances.yml 