# Azure Container Instances - Docker Compose 네이티브 지원!
version: '3.8'

services:
  spring-app:
    image: wjb127/spring-mybatis-postgres-app:latest
    ports:
      - "80:8080"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=demo_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=secure_password_123
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - postgres-db
    restart: unless-stopped

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: demo_db
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

# Azure 배포 명령어:
# az container create --resource-group myResourceGroup --file azure-container-instances.yml 