[build]
builder = "dockerfile"

[deploy]
startCommand = "mvn jetty:run"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "spring-app"

[[services]]
name = "mysql" 