name: spring-mybatis-postgres-app
services:
- name: spring-app
  source_dir: /
  github:
    repo: wjb127/java-spring-practice
    branch: main
  run_command: java -jar target/demo-1.0-SNAPSHOT.jar
  environment_slug: java
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DB_HOST
    scope: RUN_TIME
    type: SECRET
    value: ${postgres-db.HOSTNAME}
  - key: DB_PORT
    scope: RUN_TIME
    value: ${postgres-db.PORT}
  - key: DB_NAME
    scope: RUN_TIME
    value: ${postgres-db.DATABASE}
  - key: DB_USERNAME
    scope: RUN_TIME
    type: SECRET
    value: ${postgres-db.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: ${postgres-db.PASSWORD}

databases:
- name: postgres-db
  engine: PG
  version: "15"
  size: db-s-dev-database 